blank_issues_enabled: true
contact_links:
  - name: 🗺️ Roadmapa Projektu
    url: https://github.com/TwojaStronaWWW/katosalsahub/blob/main/ROADMAP.md
    about: Sprawdź zaplanowane sprinty i zadania w oficjalnej Roadmapie.
  - name: 💬 Dołącz do społeczności
    url: https://www.facebook.com/groups/519446499987373
    about: Dyskusje społeczności Kato Salsa Hub na Facebooku.
