name: Deploy Staging to LH
on:
  push:
    branches: [ "staging" ]

jobs:
  deploy-staging:
    name: Deploy staging na serwer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload via SFTP
        run: |
          sudo apt-get install -y -qq lftp > /dev/null 2>&1
          lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" \
            -p 40022 \
            sftp://${{ secrets.FTP_SERVER }} \
            -e "
              set net:timeout 60;
              set sftp:auto-confirm yes;
              mirror -R --verbose ./katosalsahub.pl /home/platne/serwer417204/public_html/staging.katosalsahub.pl;
              mirror -R --verbose ./dancepuls.pl /home/platne/serwer417204/public_html/staging.katosalsahub.pl/dancepuls;
              quit
            "
