name: Deploy to LH
on:
  push:
    branches: [ "main", "staging" ]

jobs:
  deploy:
    name: Deploy na serwer (${{ github.ref_name }})
    runs-on: ubuntu-latest
    env:
      MAIN_PATH: ${{ github.ref_name == 'main' && 'katosalsahub.pl' || 'staging.katosalsahub.pl' }}
      DANCE_PATH: ${{ github.ref_name == 'main' && 'dancepuls.katosalsahub.pl' || 'staging.katosalsahub.pl/dancepuls' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload via SFTP
        run: |
          sudo apt-get install -y -qq lftp > /dev/null 2>&1
          lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" \
            -p 40022 \
            sftp://${{ secrets.FTP_SERVER }} \
            -e "
              set net:timeout 60;
              set sftp:auto-confirm yes;
              mirror -R --verbose ./katosalsahub.pl /home/platne/serwer417204/public_html/${{ env.MAIN_PATH }};
              mirror -R --verbose ./dancepuls.pl /home/platne/serwer417204/public_html/${{ env.DANCE_PATH }};
              quit
            "
